### ISSUE TITLE
Undefined function or variable 'graph'.

### ISSUE THREAD

**Issue by Jiankai-Sun** [horverno/sze-academic-robotics-projects#2] opened 2017-07-10 12:57 UTC
When I run  CoveragePathPlanningBoustrophedon.m under directory sze-academic-robotics-projects\RobotGridCoveragePathPlanning, there is an error. 

```matlab
>> CoveragePathPlanningBoustrophedon
IdleTimeout has been reached.
Parallel pool using the 'local' profile is shutting down.
Critical displayed, next step: decomposing map into sub-poygons.
Sub-poygon decomposed map displayed, next step display connectivity graph.
Starting parallel pool (parpool) using the 'local' profile ... connected to 2 workers.
Number of iteration is:3/4
Number of iteration is:4/4
Number of iteration is:1/4
Number of iteration is:2/4
Undefined function or variable 'graph'.

Error in CoveragePathPlanningBoustrophedon (line 151)
cellGraph = graph(cellGraphSource, cellGraphTarget);
```
My Environment:

>  ver
> 
> MATLAB Version: 8.5.0.197613 (R2015a)
MATLAB License Number: 161052
Operating System: Microsoft Windows 10  Version 10.0 (Build 15063)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
> 
>MATLAB                                                Version 8.5        (R2015a)
Simulink                                              Version 8.5        (R2015a)
Aerospace Blockset                                    Version 3.15       (R2015a)
Aerospace Toolbox                                     Version 2.15       (R2015a)
Antenna Toolbox                                       Version 1.0        (R2015a)
Bioinformatics Toolbox                                Version 4.5.1      (R2015a)
Communications System Toolbox                         Version 6.0        (R2015a)
Computer Vision System Toolbox                        Version 6.2        (R2015a)
Control System Toolbox                                Version 9.9        (R2015a)
Curve Fitting Toolbox                                 Version 3.5.1      (R2015a)
DO Qualification Kit                                  Version 2.5        (R2015a)
DSP System Toolbox                                    Version 9.0        (R2015a)
Data Acquisition Toolbox                              Version 3.7        (R2015a)
Database Toolbox                                      Version 5.2.1      (R2015a)
Datafeed Toolbox                                      Version 5.1        (R2015a)
Econometrics Toolbox                                  Version 3.2        (R2015a)
Embedded Coder                                        Version 6.8        (R2015a)
Filter Design HDL Coder                               Version 2.9.7      (R2015a)
Financial Instruments Toolbox                         Version 2.1        (R2015a)
Financial Toolbox                                     Version 5.5        (R2015a)
Fixed-Point Designer                                  Version 5.0        (R2015a)
Fuzzy Logic Toolbox                                   Version 2.2.21     (R2015a)
Global Optimization Toolbox                           Version 3.3.1      (R2015a)
HDL Coder                                             Version 3.6        (R2015a)
HDL Verifier                                          Version 4.6        (R2015a)
IEC Certification Kit                                 Version 3.5        (R2015a)
Image Acquisition Toolbox                             Version 4.9        (R2015a)
Image Processing Toolbox                              Version 9.2        (R2015a)
Instrument Control Toolbox                            Version 3.7        (R2015a)
LTE System Toolbox                                    Version 2.0        (R2015a)
MATLAB Coder                                          Version 2.8        (R2015a)
MATLAB Compiler                                       Version 6.0        (R2015a)
MATLAB Compiler SDK                                   Version 6.0        (R2015a)
MATLAB Distributed Computing Server                   Version 6.6        (R2015a)
MATLAB Report Generator                               Version 4.1        (R2015a)
Mapping Toolbox                                       Version 4.1        (R2015a)
Model Predictive Control Toolbox                      Version 5.0.1      (R2015a)
Model-Based Calibration Toolbox                       Version 4.8.1      (R2015a)
Neural Network Toolbox                                Version 8.3        (R2015a)
OPC Toolbox                                           Version 3.3.3      (R2015a)
Optimization Toolbox                                  Version 7.2        (R2015a)
Parallel Computing Toolbox                            Version 6.6        (R2015a)
Partial Differential Equation Toolbox                 Version 2.0        (R2015a)
Phased Array System Toolbox                           Version 3.0        (R2015a)
Polyspace Bug Finder                                  Version 1.3        (R2015a)
Polyspace Code Prover                                 Version 9.3        (R2015a)
RF Toolbox                                            Version 2.16       (R2015a)
Robotics System Toolbox                               Version 1.0        (R2015a)
Robust Control Toolbox                                Version 5.3        (R2015a)
Signal Processing Toolbox                             Version 7.0        (R2015a)
SimBiology                                            Version 5.2        (R2015a)
SimDriveline                                          Version 2.8        (R2015a)
SimElectronics                                        Version 2.7        (R2015a)
SimEvents                                             Version 4.4        (R2015a)
SimHydraulics                                         Version 1.16       (R2015a)
SimMechanics                                          Version 4.6        (R2015a)
SimPowerSystems                                       Version 6.3        (R2015a)
SimRF                                                 Version 4.4        (R2015a)
Simscape                                              Version 3.13       (R2015a)
Simulink 3D Animation                                 Version 7.3        (R2015a)
Simulink Code Inspector                               Version 2.3        (R2015a)
Simulink Coder                                        Version 8.8        (R2015a)
Simulink Control Design                               Version 4.2        (R2015a)
Simulink Design Optimization                          Version 2.7        (R2015a)
Simulink Design Verifier                              Version 2.8        (R2015a)
Simulink Desktop Real-Time                            Version 5.0        (R2015a)
Simulink PLC Coder                                    Version 1.9        (R2015a)
Simulink Real-Time                                    Version 6.2        (R2015a)
Simulink Report Generator                             Version 4.1        (R2015a)
Simulink Test                                         Version 1.0        (R2015a)
Simulink Verification and Validation                  Version 3.9        (R2015a)
Spreadsheet Link EX                                   Version 3.2.3      (R2015a)
Stateflow                                             Version 8.5        (R2015a)
Statistics and Machine Learning Toolbox               Version 10.0       (R2015a)
Symbolic Math Toolbox                                 Version 6.2        (R2015a)
System Identification Toolbox                         Version 9.2        (R2015a)
SystemTest                                            Version 2.6.9      (R2015a)
Trading Toolbox                                       Version 2.2        (R2015a)
Vehicle Network Toolbox                               Version 2.4        (R2015a)
Vision HDL Toolbox                                    Version 1.0        (R2015a)
Wavelet Toolbox                                       Version 4.14.1     (R2015a)

**Comment by Jiankai-Sun** [comment] 2017-07-11 01:26
I have understood the above problem. Matlab 2015b is needed.
But new problem comes out.
```matlab
>>CoveragePathPlanningBoustrophedon
Critical displayed, next step: decomposing map into sub-poygons.
Sub-poygon decomposed map displayed, next step display connectivity graph.
Number of iteration is:1/9
Number of iteration is:4/9
Number of iteration is:5/9
Number of iteration is:6/9
Number of iteration is:7/9
Number of iteration is:8/9
Number of iteration is:9/9
Number of iteration is:2/9
Number of iteration is:3/9
     1     2     5     3     1     4     5     6     9     7     5     8

Undefined function or variable  'IsocProbRoadmap'.

Error in CoveragePathPlanningBoustrophedon (line 240)
                probRoadmapPath = IsocProbRoadmap((flipud(mapOriginal)),  fliplr(subXY{i}(end,:)), fliplr(subXY{i+1}(end,:))); %flipud
                fliplr
```

**Comment by Forrest-Z** [comment] 2017-08-30 14:17
i got the same problem,did you solve it ？

**Comment by ChaoyongChen1** [comment] 2019-03-29 08:15
@Jiankai-Sun  Dear friend
 I got the same problem.Can you tell me how to solve it? Thank you very much!

**Comment by ChaoyongChen1** [comment] 2019-03-29 08:18
@Forrest-Z   Hi,did you solve it recently?

**Comment by ChaoyongChen1** [comment] 2019-03-29 11:02
Dear Dr.Horváth,
  I have some troubles in running your code. It shows Undefined function or variable 'IsoProbRoadmap'.Please tell me how to solve it. Thank you very much.

**Comment by horverno** [comment] 2019-03-31 11:15
I will have a look at the issue,  the problem is that this project is a really old one, but I will do my best to find the solution. When I found it I will commit it.

**Comment by ChaoyongChen1** [comment] 2019-03-31 11:18
@horverno Thanks, it will be very helpful for me.

**Comment by horverno** [comment] 2019-04-08 07:37
I fixed the issue, some files were missing from the github repository. I committed them, the problem is that it is not the final version (which is available as a paper). The reason for that I did not wanted to commit until the paper is published, but the publishing process took almost 2 years and i lost the final version. I will do my best to re-write it in the future but now I am busy with other projects, so it may take time. The hotfix is avaiable on the "Issue #2 hotfix" branch.

**Closed as completed by horverno** 2019-04-08 07:37 UTC

**Comment by khalilzbiss** [comment] 2019-12-01 20:21
I am having a similar problem, I am getting "Undefined function or variable 'IsocProbRoadmap'." error

Thank you for sharing the code.

**Comment by JimmyFroost** [comment] 2019-12-30 13:08
Same problem for me :
I found the file as you wrote it, [HERE](https://github.com/horverno/sze-academic-robotics-projects/tree/issue-2-hotfix/RobotGridCoveragePathPlanning
 )
We also need the Statistics toolbox in order to use pdist(), but that's not the worst issue.

Thanks for sharing your work.
